### ISSUE TITLE
PlatformException already requesting permissions

### ISSUE THREAD

**Issue by dephiloper** [LB31/HikingForNerds#137]
<img width="960" alt="exception" src="https://user-images.githubusercontent.com/19599410/72750103-30646e00-3bbc-11ea-98de-9316fe221bdd.PNG">

**Comment by NovalisTheMagician** [comment]
the issue is that, for some reason, the widget is being created twice and thus requests permission twice before the first one is handled. I fixed it by introducing a static field which gets set when a request is in progress and cleared when the request is done (irrespective whether it's granted or not)
