### ISSUE TITLE
Convert pbf data to mbtiles

### ISSUE THREAD

**Issue by dephiloper** [LB31/HikingForNerds#27]
Use mapnik to convert osm data to mbtiles with shapefiles.
Research can we use osm as input for the gl tile server.

**Comment by NovalisTheMagician** [comment]
# Conversion workflow
In order for us to convert map data from geofabrik into a usable format (.mbtiles) for our tileserver / offline usage, we need two tools: 
- [tippecanoe](https://github.com/mapbox/tippecanoe)
- [ogr2ogr](https://gdal.org/programs/ogr2ogr.html)

tippecanoe is used to convert geojson data into vector-mbtiles. It also has the ability to specify a max zoom-level, at which the details of the mapdata would be illegible to see. 

Unfortunatly [geofabrik](http://download.geofabrik.de) doesn't provide its mapdata in the geojson format, but it gives us data in shapefile form. And this is where ogr2ogr comes into play.
ogr2ogr is a tool from a bigger (gdal)[https://gdal.org/index.html] library, which is used to convert between multiple gis dataformats. With this tool we can convert the shapefiles into geojson.
Installation is quite the pain, compiling from source requires a big list of dependencies and installing compiled binaries requires a package-manager [conda](https://anaconda.org). Fortunatly for us, if we only update and prepare the maps manually we can use an [online version](https://ogre.adc4gis.com) of the ogr2ogr tool.

With these tools the workflow of updating/providing map data to the server is:
1. Get the respective (shapefiles)[http://download.geofabrik.de/europe/germany.html] from geofabrik
2. Convert the shapefile into a geojson (just provide the zip for the file)
3. Convert the geojson into mbtiles using the command 'tippecanoe -zg -o out.mbtiles --drop-densest-as-needed in.json', where the -o switch sets the output filename
4. Profit*

*There's just one small issue: the mapbox plugin doesn't support local mbtiles as mapsources (for offline use). Fortunatly if we provide a mabox compatible map-stylesheet, then we can use the same method of getting a cached database version of the map. In the mapbox tool 'mbgl-offline' with just have to provide the style-url of our tileserver style.

Finally in the attachment, I'll provide a convert mbtile of berlin (in a zip because github).
~[berlin.zip](https://github.com/LB31/HikingForNerds/files/3919795/berlin.zip)~

Fixed version:
[berlin.zip](https://github.com/LB31/HikingForNerds/files/3921357/berlin.zip)
