### ISSUE TITLE
React

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#3]
Research to React. Explain all other team members what advantages this has against other methods..

**Comment by mayo-s** [comment]
I believe I should start of with the most popular comments on "ReactJS vs React Native"

"ReactJS is a JavaScript library, supporting both front-end web and being run on a server, for building user interfaces and web applications.

React Native is a mobile framework that compiles to native app components, allowing you to build native mobile applications for different platforms (iOS, Android, and Windows Mobile) in JavaScript that allows you to use ReactJS to build your components, and implements ReactJS under the hood."

Concidering that, we should decide which direction we would like to go since it is not 100% interchangeable.

In case we decide for a web version, there are multiple ways to make them look good on desktop and mobile devices. I did not look further into it, but there are also option to make those available offline as well.

Since React is open source and quite popular there are lots of libraries for our needs.
i.e. Leaflet is probably the leading JS library for interactive maps, there are also react components available to make use of these unless we want to use the leaflet API directly.
Furthermore are the ways to make waypoints offline available (e.g. https://www.npmjs.com/package/gps-to-gpx)

As mentioned above, we need to decide what we want as our outcome. If it is primarly a web version than reactJS is a good choice.
